FROM openjdk:8u265

WORKDIR /mnt
COPY SimpleFileInOutJob_run.sh .
COPY lib lib
COPY testing testing
COPY simplefileinoutjob_0_1.jar  .
COPY mnt/inputFile.csv .
#ENTRYPOINT ./SimpleFileInOutJob_run.sh
